[project]
name = "jats-importexport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
dev = [
    "ruff>=0.9",
    "ty>=0.0.40",
    "pre-commit>=4.6.0"
]

[tool.uv.workspace]
members = ["packages/*","applications/*"]

[tool.ruff]
line-length = 120
target-version = "py313"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = []

[tool.ty.environment]
python-version = "3.13"

[tool.uv.sources]
jats_classes = {workspace = true}
