# coding: utf-8

# flake8: noqa

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0a8"

# Define package exports
__all__ = [
    "ExportApi",
    "StatusApi",
    "UploadApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CacheClearedResponse",
    "CacheStatusResponse",
    "HTTP400BadRequest",
    "HTTP413PayloadTooLarge",
    "HTTP415UnsupportedMediaType",
    "HTTP500InternalServerError",
    "HTTPValidationError",
    "HtmlDocumentResponse",
    "JatsDocumentResponse",
    "LocationInner",
    "MarkdownDocumentResponse",
    "UploadFileResponse",
    "UploadXmlRequest1",
    "UploadZipRequest1",
    "ValidationError",
]

# import apis into sdk package
from jats_importexport_client.api.export_api import ExportApi as ExportApi
from jats_importexport_client.api.status_api import StatusApi as StatusApi
from jats_importexport_client.api.upload_api import UploadApi as UploadApi

# import ApiClient
from jats_importexport_client.api_response import ApiResponse as ApiResponse
from jats_importexport_client.api_client import ApiClient as ApiClient
from jats_importexport_client.configuration import Configuration as Configuration
from jats_importexport_client.exceptions import OpenApiException as OpenApiException
from jats_importexport_client.exceptions import ApiTypeError as ApiTypeError
from jats_importexport_client.exceptions import ApiValueError as ApiValueError
from jats_importexport_client.exceptions import ApiKeyError as ApiKeyError
from jats_importexport_client.exceptions import ApiAttributeError as ApiAttributeError
from jats_importexport_client.exceptions import ApiException as ApiException

# import models into sdk package
from jats_importexport_client.models.cache_cleared_response import CacheClearedResponse as CacheClearedResponse
from jats_importexport_client.models.cache_status_response import CacheStatusResponse as CacheStatusResponse
from jats_importexport_client.models.http400_bad_request import HTTP400BadRequest as HTTP400BadRequest
from jats_importexport_client.models.http413_payload_too_large import HTTP413PayloadTooLarge as HTTP413PayloadTooLarge
from jats_importexport_client.models.http415_unsupported_media_type import HTTP415UnsupportedMediaType as HTTP415UnsupportedMediaType
from jats_importexport_client.models.http500_internal_server_error import HTTP500InternalServerError as HTTP500InternalServerError
from jats_importexport_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from jats_importexport_client.models.html_document_response import HtmlDocumentResponse as HtmlDocumentResponse
from jats_importexport_client.models.jats_document_response import JatsDocumentResponse as JatsDocumentResponse
from jats_importexport_client.models.location_inner import LocationInner as LocationInner
from jats_importexport_client.models.markdown_document_response import MarkdownDocumentResponse as MarkdownDocumentResponse
from jats_importexport_client.models.upload_file_response import UploadFileResponse as UploadFileResponse
from jats_importexport_client.models.upload_xml_request1 import UploadXmlRequest1 as UploadXmlRequest1
from jats_importexport_client.models.upload_zip_request1 import UploadZipRequest1 as UploadZipRequest1
from jats_importexport_client.models.validation_error import ValidationError as ValidationError

