# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a43
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ExportType(str, Enum):
    """
    ExportType
    """

    """
    allowed enum values
    """
    HTML = 'html'
    HTML_EDIT_LINKS = 'html_edit_links'
    MD = 'md'
    MD_EDIT_LINKS = 'md_edit_links'
    JATS = 'jats'
    PDF = 'pdf'
    METADATA = 'metadata'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ExportType from a JSON string"""
        return cls(json.loads(json_str))


