# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a24
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Front(BaseModel):
    """
    Represents a JATS <front> element containing article metadata.
    """ # noqa: E501
    journal_id: Optional[StrictStr]
    journal_title: Optional[StrictStr]
    journal_subtitle: Optional[StrictStr]
    issn: Optional[StrictStr]
    publisher_name: Optional[StrictStr]
    publisher_institution: Optional[StrictStr]
    publisher_addr_line: Optional[StrictStr]
    publisher_postal_code: Optional[StrictStr]
    publisher_city: Optional[StrictStr]
    publisher_phone: Optional[StrictStr]
    publisher_email: Optional[StrictStr]
    publisher_uri: Optional[StrictStr]
    article_id: Optional[StrictStr]
    title: Optional[StrictStr]
    article_subtitle: List[StrictStr]
    author_surname: Optional[StrictStr]
    co_author_surname: Optional[StrictStr]
    co_author_aff: Optional[StrictStr]
    self_uri: Optional[StrictStr]
    article_categories: Optional[StrictStr]
    pub_date_ausgabedatum: Optional[date]
    pub_date_aktualisierte_fassung: Optional[date]
    history_initial_publication: Optional[StrictStr]
    history_correction: Optional[StrictStr]
    history_latest_version: Optional[StrictStr]
    copyright_statement: Optional[StrictStr]
    copyright_holder: Optional[StrictStr]
    abstract_short_title: Optional[StrictStr]
    abstract_short: Optional[StrictStr]
    abstract_summary_title: Optional[StrictStr]
    abstract_summary: Optional[StrictStr]
    keywords: Optional[List[StrictStr]]
    beschreibender_typ: Optional[StrictStr]
    bisherige_bestellnummer: Optional[StrictStr]
    webcode: Optional[StrictStr]
    organisationseinheit: Optional[StrictStr]
    fachbereich: Optional[StrictStr]
    sachgebiet: Optional[StrictStr]
    veroeffentlichungsstatus: Optional[StrictStr]
    bildnachweis: Optional[StrictStr]
    ueberschriften_mit_nummerierung: Optional[StrictBool]
    __properties: ClassVar[List[str]] = ["journal_id", "journal_title", "journal_subtitle", "issn", "publisher_name", "publisher_institution", "publisher_addr_line", "publisher_postal_code", "publisher_city", "publisher_phone", "publisher_email", "publisher_uri", "article_id", "title", "article_subtitle", "author_surname", "co_author_surname", "co_author_aff", "self_uri", "article_categories", "pub_date_ausgabedatum", "pub_date_aktualisierte_fassung", "history_initial_publication", "history_correction", "history_latest_version", "copyright_statement", "copyright_holder", "abstract_short_title", "abstract_short", "abstract_summary_title", "abstract_summary", "keywords", "beschreibender_typ", "bisherige_bestellnummer", "webcode", "organisationseinheit", "fachbereich", "sachgebiet", "veroeffentlichungsstatus", "bildnachweis", "ueberschriften_mit_nummerierung"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Front from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if journal_id (nullable) is None
        # and model_fields_set contains the field
        if self.journal_id is None and "journal_id" in self.model_fields_set:
            _dict['journal_id'] = None

        # set to None if journal_title (nullable) is None
        # and model_fields_set contains the field
        if self.journal_title is None and "journal_title" in self.model_fields_set:
            _dict['journal_title'] = None

        # set to None if journal_subtitle (nullable) is None
        # and model_fields_set contains the field
        if self.journal_subtitle is None and "journal_subtitle" in self.model_fields_set:
            _dict['journal_subtitle'] = None

        # set to None if issn (nullable) is None
        # and model_fields_set contains the field
        if self.issn is None and "issn" in self.model_fields_set:
            _dict['issn'] = None

        # set to None if publisher_name (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_name is None and "publisher_name" in self.model_fields_set:
            _dict['publisher_name'] = None

        # set to None if publisher_institution (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_institution is None and "publisher_institution" in self.model_fields_set:
            _dict['publisher_institution'] = None

        # set to None if publisher_addr_line (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_addr_line is None and "publisher_addr_line" in self.model_fields_set:
            _dict['publisher_addr_line'] = None

        # set to None if publisher_postal_code (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_postal_code is None and "publisher_postal_code" in self.model_fields_set:
            _dict['publisher_postal_code'] = None

        # set to None if publisher_city (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_city is None and "publisher_city" in self.model_fields_set:
            _dict['publisher_city'] = None

        # set to None if publisher_phone (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_phone is None and "publisher_phone" in self.model_fields_set:
            _dict['publisher_phone'] = None

        # set to None if publisher_email (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_email is None and "publisher_email" in self.model_fields_set:
            _dict['publisher_email'] = None

        # set to None if publisher_uri (nullable) is None
        # and model_fields_set contains the field
        if self.publisher_uri is None and "publisher_uri" in self.model_fields_set:
            _dict['publisher_uri'] = None

        # set to None if article_id (nullable) is None
        # and model_fields_set contains the field
        if self.article_id is None and "article_id" in self.model_fields_set:
            _dict['article_id'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if author_surname (nullable) is None
        # and model_fields_set contains the field
        if self.author_surname is None and "author_surname" in self.model_fields_set:
            _dict['author_surname'] = None

        # set to None if co_author_surname (nullable) is None
        # and model_fields_set contains the field
        if self.co_author_surname is None and "co_author_surname" in self.model_fields_set:
            _dict['co_author_surname'] = None

        # set to None if co_author_aff (nullable) is None
        # and model_fields_set contains the field
        if self.co_author_aff is None and "co_author_aff" in self.model_fields_set:
            _dict['co_author_aff'] = None

        # set to None if self_uri (nullable) is None
        # and model_fields_set contains the field
        if self.self_uri is None and "self_uri" in self.model_fields_set:
            _dict['self_uri'] = None

        # set to None if article_categories (nullable) is None
        # and model_fields_set contains the field
        if self.article_categories is None and "article_categories" in self.model_fields_set:
            _dict['article_categories'] = None

        # set to None if pub_date_ausgabedatum (nullable) is None
        # and model_fields_set contains the field
        if self.pub_date_ausgabedatum is None and "pub_date_ausgabedatum" in self.model_fields_set:
            _dict['pub_date_ausgabedatum'] = None

        # set to None if pub_date_aktualisierte_fassung (nullable) is None
        # and model_fields_set contains the field
        if self.pub_date_aktualisierte_fassung is None and "pub_date_aktualisierte_fassung" in self.model_fields_set:
            _dict['pub_date_aktualisierte_fassung'] = None

        # set to None if history_initial_publication (nullable) is None
        # and model_fields_set contains the field
        if self.history_initial_publication is None and "history_initial_publication" in self.model_fields_set:
            _dict['history_initial_publication'] = None

        # set to None if history_correction (nullable) is None
        # and model_fields_set contains the field
        if self.history_correction is None and "history_correction" in self.model_fields_set:
            _dict['history_correction'] = None

        # set to None if history_latest_version (nullable) is None
        # and model_fields_set contains the field
        if self.history_latest_version is None and "history_latest_version" in self.model_fields_set:
            _dict['history_latest_version'] = None

        # set to None if copyright_statement (nullable) is None
        # and model_fields_set contains the field
        if self.copyright_statement is None and "copyright_statement" in self.model_fields_set:
            _dict['copyright_statement'] = None

        # set to None if copyright_holder (nullable) is None
        # and model_fields_set contains the field
        if self.copyright_holder is None and "copyright_holder" in self.model_fields_set:
            _dict['copyright_holder'] = None

        # set to None if abstract_short_title (nullable) is None
        # and model_fields_set contains the field
        if self.abstract_short_title is None and "abstract_short_title" in self.model_fields_set:
            _dict['abstract_short_title'] = None

        # set to None if abstract_short (nullable) is None
        # and model_fields_set contains the field
        if self.abstract_short is None and "abstract_short" in self.model_fields_set:
            _dict['abstract_short'] = None

        # set to None if abstract_summary_title (nullable) is None
        # and model_fields_set contains the field
        if self.abstract_summary_title is None and "abstract_summary_title" in self.model_fields_set:
            _dict['abstract_summary_title'] = None

        # set to None if abstract_summary (nullable) is None
        # and model_fields_set contains the field
        if self.abstract_summary is None and "abstract_summary" in self.model_fields_set:
            _dict['abstract_summary'] = None

        # set to None if keywords (nullable) is None
        # and model_fields_set contains the field
        if self.keywords is None and "keywords" in self.model_fields_set:
            _dict['keywords'] = None

        # set to None if beschreibender_typ (nullable) is None
        # and model_fields_set contains the field
        if self.beschreibender_typ is None and "beschreibender_typ" in self.model_fields_set:
            _dict['beschreibender_typ'] = None

        # set to None if bisherige_bestellnummer (nullable) is None
        # and model_fields_set contains the field
        if self.bisherige_bestellnummer is None and "bisherige_bestellnummer" in self.model_fields_set:
            _dict['bisherige_bestellnummer'] = None

        # set to None if webcode (nullable) is None
        # and model_fields_set contains the field
        if self.webcode is None and "webcode" in self.model_fields_set:
            _dict['webcode'] = None

        # set to None if organisationseinheit (nullable) is None
        # and model_fields_set contains the field
        if self.organisationseinheit is None and "organisationseinheit" in self.model_fields_set:
            _dict['organisationseinheit'] = None

        # set to None if fachbereich (nullable) is None
        # and model_fields_set contains the field
        if self.fachbereich is None and "fachbereich" in self.model_fields_set:
            _dict['fachbereich'] = None

        # set to None if sachgebiet (nullable) is None
        # and model_fields_set contains the field
        if self.sachgebiet is None and "sachgebiet" in self.model_fields_set:
            _dict['sachgebiet'] = None

        # set to None if veroeffentlichungsstatus (nullable) is None
        # and model_fields_set contains the field
        if self.veroeffentlichungsstatus is None and "veroeffentlichungsstatus" in self.model_fields_set:
            _dict['veroeffentlichungsstatus'] = None

        # set to None if bildnachweis (nullable) is None
        # and model_fields_set contains the field
        if self.bildnachweis is None and "bildnachweis" in self.model_fields_set:
            _dict['bildnachweis'] = None

        # set to None if ueberschriften_mit_nummerierung (nullable) is None
        # and model_fields_set contains the field
        if self.ueberschriften_mit_nummerierung is None and "ueberschriften_mit_nummerierung" in self.model_fields_set:
            _dict['ueberschriften_mit_nummerierung'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Front from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "journal_id": obj.get("journal_id"),
            "journal_title": obj.get("journal_title"),
            "journal_subtitle": obj.get("journal_subtitle"),
            "issn": obj.get("issn"),
            "publisher_name": obj.get("publisher_name"),
            "publisher_institution": obj.get("publisher_institution"),
            "publisher_addr_line": obj.get("publisher_addr_line"),
            "publisher_postal_code": obj.get("publisher_postal_code"),
            "publisher_city": obj.get("publisher_city"),
            "publisher_phone": obj.get("publisher_phone"),
            "publisher_email": obj.get("publisher_email"),
            "publisher_uri": obj.get("publisher_uri"),
            "article_id": obj.get("article_id"),
            "title": obj.get("title"),
            "article_subtitle": obj.get("article_subtitle"),
            "author_surname": obj.get("author_surname"),
            "co_author_surname": obj.get("co_author_surname"),
            "co_author_aff": obj.get("co_author_aff"),
            "self_uri": obj.get("self_uri"),
            "article_categories": obj.get("article_categories"),
            "pub_date_ausgabedatum": obj.get("pub_date_ausgabedatum"),
            "pub_date_aktualisierte_fassung": obj.get("pub_date_aktualisierte_fassung"),
            "history_initial_publication": obj.get("history_initial_publication"),
            "history_correction": obj.get("history_correction"),
            "history_latest_version": obj.get("history_latest_version"),
            "copyright_statement": obj.get("copyright_statement"),
            "copyright_holder": obj.get("copyright_holder"),
            "abstract_short_title": obj.get("abstract_short_title"),
            "abstract_short": obj.get("abstract_short"),
            "abstract_summary_title": obj.get("abstract_summary_title"),
            "abstract_summary": obj.get("abstract_summary"),
            "keywords": obj.get("keywords"),
            "beschreibender_typ": obj.get("beschreibender_typ"),
            "bisherige_bestellnummer": obj.get("bisherige_bestellnummer"),
            "webcode": obj.get("webcode"),
            "organisationseinheit": obj.get("organisationseinheit"),
            "fachbereich": obj.get("fachbereich"),
            "sachgebiet": obj.get("sachgebiet"),
            "veroeffentlichungsstatus": obj.get("veroeffentlichungsstatus"),
            "bildnachweis": obj.get("bildnachweis"),
            "ueberschriften_mit_nummerierung": obj.get("ueberschriften_mit_nummerierung")
        })
        return _obj


