# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a10
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.upload_docx_request1 import UploadDocxRequest1

class TestUploadDocxRequest1(unittest.TestCase):
    """UploadDocxRequest1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadDocxRequest1:
        """Test UploadDocxRequest1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadDocxRequest1`
        """
        model = UploadDocxRequest1()
        if include_optional:
            return UploadDocxRequest1(
                docx_file = ''
            )
        else:
            return UploadDocxRequest1(
                docx_file = '',
        )
        """

    def testUploadDocxRequest1(self):
        """Test UploadDocxRequest1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
