# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a41
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.api.export_async_api import ExportAsyncApi


class TestExportAsyncApi(unittest.TestCase):
    """ExportAsyncApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExportAsyncApi()

    def tearDown(self) -> None:
        pass

    def test_export_html_async(self) -> None:
        """Test case for export_html_async

        Export Html
        """
        pass


if __name__ == '__main__':
    unittest.main()
