# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a39
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.http404_not_found import HTTP404NotFound

class TestHTTP404NotFound(unittest.TestCase):
    """HTTP404NotFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTP404NotFound:
        """Test HTTP404NotFound
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HTTP404NotFound`
        """
        model = HTTP404NotFound()
        if include_optional:
            return HTTP404NotFound(
                detail = 'The requested resource was not found.'
            )
        else:
            return HTTP404NotFound(
        )
        """

    def testHTTP404NotFound(self):
        """Test HTTP404NotFound"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
