# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a21
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.list_batching import ListBatching

class TestListBatching(unittest.TestCase):
    """ListBatching unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBatching:
        """Test ListBatching
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBatching`
        """
        model = ListBatching()
        if include_optional:
            return ListBatching(
                current = '',
                next = '',
                previous = '',
                first = '',
                last = ''
            )
        else:
            return ListBatching(
                current = '',
                next = '',
                previous = '',
                first = '',
                last = '',
        )
        """

    def testListBatching(self):
        """Test ListBatching"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
