# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.http415_unsupported_media_type import HTTP415UnsupportedMediaType

class TestHTTP415UnsupportedMediaType(unittest.TestCase):
    """HTTP415UnsupportedMediaType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTP415UnsupportedMediaType:
        """Test HTTP415UnsupportedMediaType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HTTP415UnsupportedMediaType`
        """
        model = HTTP415UnsupportedMediaType()
        if include_optional:
            return HTTP415UnsupportedMediaType(
                detail = 'Unsupported media type.'
            )
        else:
            return HTTP415UnsupportedMediaType(
        )
        """

    def testHTTP415UnsupportedMediaType(self):
        """Test HTTP415UnsupportedMediaType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
