# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a43
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.list_fachbereiche_tree_response import ListFachbereicheTreeResponse

class TestListFachbereicheTreeResponse(unittest.TestCase):
    """ListFachbereicheTreeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListFachbereicheTreeResponse:
        """Test ListFachbereicheTreeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListFachbereicheTreeResponse`
        """
        model = ListFachbereicheTreeResponse()
        if include_optional:
            return ListFachbereicheTreeResponse(
                fachbereiche = [
                    jats_importexport_client.models.list_fachbereich_with_sachgebiete.ListFachbereichWithSachgebiete(
                        fachbereich = '', 
                        sachgebiete = [
                            ''
                            ], )
                    ]
            )
        else:
            return ListFachbereicheTreeResponse(
                fachbereiche = [
                    jats_importexport_client.models.list_fachbereich_with_sachgebiete.ListFachbereichWithSachgebiete(
                        fachbereich = '', 
                        sachgebiete = [
                            ''
                            ], )
                    ],
        )
        """

    def testListFachbereicheTreeResponse(self):
        """Test ListFachbereicheTreeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
