# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a41
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.export_type import ExportType

class TestExportType(unittest.TestCase):
    """ExportType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportType(self):
        """Test ExportType"""
        # inst = ExportType()

if __name__ == '__main__':
    unittest.main()
