# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.markdown_document_response import MarkdownDocumentResponse

class TestMarkdownDocumentResponse(unittest.TestCase):
    """MarkdownDocumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MarkdownDocumentResponse:
        """Test MarkdownDocumentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MarkdownDocumentResponse`
        """
        model = MarkdownDocumentResponse()
        if include_optional:
            return MarkdownDocumentResponse(
                md = ''
            )
        else:
            return MarkdownDocumentResponse(
                md = '',
        )
        """

    def testMarkdownDocumentResponse(self):
        """Test MarkdownDocumentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
