# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a43
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.delete_article_response import DeleteArticleResponse

class TestDeleteArticleResponse(unittest.TestCase):
    """DeleteArticleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteArticleResponse:
        """Test DeleteArticleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteArticleResponse`
        """
        model = DeleteArticleResponse()
        if include_optional:
            return DeleteArticleResponse(
                detail = 'Errors occurred during the deletion of the referenced assets. The article was successfully deleted but some associated files could not be removed. Check the errors list for details.',
                errors = [
                    ''
                    ]
            )
        else:
            return DeleteArticleResponse(
                errors = [
                    ''
                    ],
        )
        """

    def testDeleteArticleResponse(self):
        """Test DeleteArticleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
