"""
JATS Import/Export API

An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from jats_importexport_client.models.http500_internal_server_error import HTTP500InternalServerError


class TestHTTP500InternalServerError(unittest.TestCase):
    """HTTP500InternalServerError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTP500InternalServerError:
        """Test HTTP500InternalServerError
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HTTP500InternalServerError`
        """
        model = HTTP500InternalServerError()
        if include_optional:
            return HTTP500InternalServerError(
                detail = 'An unexpected error occurred.'
            )
        else:
            return HTTP500InternalServerError(
        )
        """

    def testHTTP500InternalServerError(self):
        """Test HTTP500InternalServerError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
