# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.api.status_api import StatusApi


class TestStatusApi(unittest.IsolatedAsyncioTestCase):
    """StatusApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = StatusApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_health_status_status_get(self) -> None:
        """Test case for health_status_status_get

        Health Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
