# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a19
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.api.list_api import ListApi


class TestListApi(unittest.TestCase):
    """ListApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ListApi()

    def tearDown(self) -> None:
        pass

    def test_list_articles(self) -> None:
        """Test case for list_articles

        List Articles
        """
        pass


if __name__ == '__main__':
    unittest.main()
