# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a27
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.api.modify_api import ModifyApi


class TestModifyApi(unittest.TestCase):
    """ModifyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ModifyApi()

    def tearDown(self) -> None:
        pass

    def test_link_related_articles(self) -> None:
        """Test case for link_related_articles

        Link related articles IDs to the real articles in the storage
        """
        pass


if __name__ == '__main__':
    unittest.main()
