# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a39
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.http409_conflict import HTTP409Conflict

class TestHTTP409Conflict(unittest.TestCase):
    """HTTP409Conflict unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTP409Conflict:
        """Test HTTP409Conflict
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HTTP409Conflict`
        """
        model = HTTP409Conflict()
        if include_optional:
            return HTTP409Conflict(
                detail = 'Conflict.'
            )
        else:
            return HTTP409Conflict(
        )
        """

    def testHTTP409Conflict(self):
        """Test HTTP409Conflict"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
