"""
JATS Import/Export API

An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from jats_importexport_client.models.http400_bad_request import HTTP400BadRequest


class TestHTTP400BadRequest(unittest.TestCase):
    """HTTP400BadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTP400BadRequest:
        """Test HTTP400BadRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `HTTP400BadRequest`
        """
        model = HTTP400BadRequest()
        if include_optional:
            return HTTP400BadRequest(
                detail = 'Bad request.'
            )
        else:
            return HTTP400BadRequest(
        )
        """

    def testHTTP400BadRequest(self):
        """Test HTTP400BadRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
