# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a27
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.update_articles_response import UpdateArticlesResponse

class TestUpdateArticlesResponse(unittest.TestCase):
    """UpdateArticlesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateArticlesResponse:
        """Test UpdateArticlesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateArticlesResponse`
        """
        model = UpdateArticlesResponse()
        if include_optional:
            return UpdateArticlesResponse(
                updated_articles = [
                    ''
                    ]
            )
        else:
            return UpdateArticlesResponse(
                updated_articles = [
                    ''
                    ],
        )
        """

    def testUpdateArticlesResponse(self):
        """Test UpdateArticlesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
