# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.http413_payload_too_large import HTTP413PayloadTooLarge

class TestHTTP413PayloadTooLarge(unittest.TestCase):
    """HTTP413PayloadTooLarge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTP413PayloadTooLarge:
        """Test HTTP413PayloadTooLarge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HTTP413PayloadTooLarge`
        """
        model = HTTP413PayloadTooLarge()
        if include_optional:
            return HTTP413PayloadTooLarge(
                detail = 'The uploaded file is too large.'
            )
        else:
            return HTTP413PayloadTooLarge(
        )
        """

    def testHTTP413PayloadTooLarge(self):
        """Test HTTP413PayloadTooLarge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
