# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a41
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.api.cache_management_api import CacheManagementApi


class TestCacheManagementApi(unittest.TestCase):
    """CacheManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CacheManagementApi()

    def tearDown(self) -> None:
        pass

    def test_clear_export_cache(self) -> None:
        """Test case for clear_export_cache

        Clear Export Cache
        """
        pass

    def test_get_cache_status(self) -> None:
        """Test case for get_cache_status

        Get Cache Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
