# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.api.upload_api import UploadApi


class TestUploadApi(unittest.IsolatedAsyncioTestCase):
    """UploadApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = UploadApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_upload_xml_upload_xml_post(self) -> None:
        """Test case for upload_xml_upload_xml_post

        Upload a JATS Document (XML) to the storage
        """
        pass

    async def test_upload_zip_upload_zip_post(self) -> None:
        """Test case for upload_zip_upload_zip_post

        Upload a JATS Document (ZIP-file) to the storage
        """
        pass


if __name__ == '__main__':
    unittest.main()
