# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.cache_cleared_response import CacheClearedResponse

class TestCacheClearedResponse(unittest.TestCase):
    """CacheClearedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CacheClearedResponse:
        """Test CacheClearedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CacheClearedResponse`
        """
        model = CacheClearedResponse()
        if include_optional:
            return CacheClearedResponse(
                message = ''
            )
        else:
            return CacheClearedResponse(
                message = '',
        )
        """

    def testCacheClearedResponse(self):
        """Test CacheClearedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
