# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a39
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.http422_unprocessable_entity import HTTP422UnprocessableEntity

class TestHTTP422UnprocessableEntity(unittest.TestCase):
    """HTTP422UnprocessableEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HTTP422UnprocessableEntity:
        """Test HTTP422UnprocessableEntity
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HTTP422UnprocessableEntity`
        """
        model = HTTP422UnprocessableEntity()
        if include_optional:
            return HTTP422UnprocessableEntity(
                detail = 'Unprocessable entity.'
            )
        else:
            return HTTP422UnprocessableEntity(
        )
        """

    def testHTTP422UnprocessableEntity(self):
        """Test HTTP422UnprocessableEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
