"""
JATS Import/Export API

An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from jats_importexport_client.api.export_api import ExportApi


class TestExportApi(unittest.IsolatedAsyncioTestCase):
    """ExportApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = ExportApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_export_html_export_html_get(self) -> None:
        """Test case for export_html_export_html_get

        Export Html
        """
        pass

    async def test_export_jats_export_jats_get(self) -> None:
        """Test case for export_jats_export_jats_get

        Export Jats
        """
        pass


if __name__ == "__main__":
    unittest.main()
