# coding: utf-8

"""
    JATS Import/Export API

    An API for uploading JATS documents, importing them to different storage backends (e.g. Plone), and converting them to various formats.

    The version of the OpenAPI document: 1.0.0a23
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jats_importexport_client.models.metadata_response import MetadataResponse

class TestMetadataResponse(unittest.TestCase):
    """MetadataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MetadataResponse:
        """Test MetadataResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MetadataResponse`
        """
        model = MetadataResponse()
        if include_optional:
            return MetadataResponse(
                metadata = jats_importexport_client.models.front.Front(
                    journal_id = '', 
                    journal_title = '', 
                    journal_subtitle = '', 
                    issn = '', 
                    publisher_name = '', 
                    publisher_institution = '', 
                    publisher_addr_line = '', 
                    publisher_postal_code = '', 
                    publisher_city = '', 
                    publisher_phone = '', 
                    publisher_email = '', 
                    publisher_uri = '', 
                    article_id = '', 
                    title = '', 
                    article_subtitle = [
                        ''
                        ], 
                    author_surname = '', 
                    co_author_surname = '', 
                    co_author_aff = '', 
                    self_uri = '', 
                    article_categories = '', 
                    pub_date_ausgabedatum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    pub_date_aktualisierte_fassung = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    history_initial_publication = '', 
                    history_correction = '', 
                    history_latest_version = '', 
                    copyright_statement = '', 
                    copyright_holder = '', 
                    abstract_short_title = '', 
                    abstract_short = '', 
                    abstract_summary_title = '', 
                    abstract_summary = '', 
                    keywords = [
                        ''
                        ], 
                    beschreibender_typ = '', 
                    bisherige_bestellnummer = '', 
                    webcode = '', 
                    organisationseinheit = '', 
                    fachbereich = '', 
                    sachgebiet = '', 
                    veroeffentlichungsstatus = '', 
                    bildnachweis = '', 
                    ueberschriften_mit_nummerierung = True, )
            )
        else:
            return MetadataResponse(
                metadata = jats_importexport_client.models.front.Front(
                    journal_id = '', 
                    journal_title = '', 
                    journal_subtitle = '', 
                    issn = '', 
                    publisher_name = '', 
                    publisher_institution = '', 
                    publisher_addr_line = '', 
                    publisher_postal_code = '', 
                    publisher_city = '', 
                    publisher_phone = '', 
                    publisher_email = '', 
                    publisher_uri = '', 
                    article_id = '', 
                    title = '', 
                    article_subtitle = [
                        ''
                        ], 
                    author_surname = '', 
                    co_author_surname = '', 
                    co_author_aff = '', 
                    self_uri = '', 
                    article_categories = '', 
                    pub_date_ausgabedatum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    pub_date_aktualisierte_fassung = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    history_initial_publication = '', 
                    history_correction = '', 
                    history_latest_version = '', 
                    copyright_statement = '', 
                    copyright_holder = '', 
                    abstract_short_title = '', 
                    abstract_short = '', 
                    abstract_summary_title = '', 
                    abstract_summary = '', 
                    keywords = [
                        ''
                        ], 
                    beschreibender_typ = '', 
                    bisherige_bestellnummer = '', 
                    webcode = '', 
                    organisationseinheit = '', 
                    fachbereich = '', 
                    sachgebiet = '', 
                    veroeffentlichungsstatus = '', 
                    bildnachweis = '', 
                    ueberschriften_mit_nummerierung = True, ),
        )
        """

    def testMetadataResponse(self):
        """Test MetadataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
