name: Build SBOM

on:
  push:
  pull_request:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: make install

      - name: Build SBOM
        run: make sbom

      - name: Publish SBOM artifact
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: sbom.json
          archive: false
          if-no-files-found: error
